### PR TITLE
docs: Added Greeting for Jonathan

### PR DESCRIPTION
**Pull request by JAlvarez6**

### CODE REVIEW

**Comment by tmajchrz** [comment]
Hi Jonathan,

It looks like you deleted my greeting.  I just want you to add yours, not delete mine (or any others).  Can you please try updating hello.txt appropriately and sending another pull request?

Regard,
Dr. M

**Review by tmajchrz — CHANGES_REQUESTED** [review]
Hi Jonathan,

It looks like you deleted my greeting.  I just want you to add yours, not delete mine (or any others).  Can you please try updating hello.txt appropriately and sending another pull request?

Regard,
Dr. M

**Comment by JAlvarez6** [comment]
Hello Professor, I reverted the changes and added the correct greeting.

**Review by tmajchrz — APPROVED** [review]
Nice work, Jonathan, Mika, and Austin! :)

**Pull request merged**
